name: unique_master_dashboard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter bloc
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # Service locator
  get_it: ^5.0.4

  # Core
  # Functional programming thingies
  dartz: ^0.9.1
  # Value equality checker - by default, dart only check equality by reference
  equatable: ^1.2.5
  # Type-safe DateTime and Duration calculations
  time: ^1.3.0
  # UUID Generator and Parser for all Dart platforms
  uuid: ^2.0.4
  # Remote API connectivity check - check if the device is connected to the internet
  data_connection_checker: ^0.3.4
  # Official connectivity plugin - this does not guarante device has internet connection
  # so may be it's just connected to a Wifi or VPN that has no internet
  connectivity: ^2.0.2

  # Dio http client
  dio: ^3.0.10

  # default Http client
  http: ^0.12.1

  # Utility Packages
  # Used to find a suitable location to store the database.
  path_provider: ^1.6.9
  path:
  package_info: ^0.4.3+2
  freezed_annotation: ^0.11.0+1
  # plugin for reading and writing simple key-value pairs to device storage
  shared_preferences: ">=0.5.8 <2.0.0"
  # BlurHash for flutter
  flutter_blurhash: any
  # Cached network image plugin
  cached_network_image: ^2.3.3
  # OctoImage to use with CachedNetworkImage
  octo_image: ^0.3.0
  # Flutter Skeleton View
  flutter_shimmer: ^1.3.0
  # custom SnackBar widget with lots of customizations
  flushbar: ^1.10.4
  # flutter SpinKit package
  flutter_spinkit: ^4.1.2+1
  # Random color generator
  random_color: ^1.0.5
  # custom dialogs
  awesome_dialog: ^1.1.3
  # Dotted Border
  dotted_border: ^1.0.6
  # Dotted line
  dotted_line: ^2.0.2
  #Locale DateTime
  intl: ^0.17.0
  # Date time picker
  flutter_rounded_date_picker: ^1.0.5
  # Html view parser
  flutter_html: ^1.1.1
  #device version info
  device_info: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking plugin
  mockito: ^4.1.1
  # code Linters
  lint: ^1.2.0
  build_runner:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        # currently, no font weight is defined for Italic font
        # - asset: assets/fonts/Montserrat-Italic.ttf

        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
